<!-- THIS TEMPLATE WAS GENERATED BY GPT-3 BUT IT KIND OF SUX -->
<!-- <template>
    <div class="container mx-auto flex items-center justify-center h-screen">
        <form class="w-full max-w-xs">
            <div class="md:flex md:items-center mb-6">
                <div class="md:w-1/3">
                    <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                        Full Name
                    </label>
                </div>
                <div class="md:w-2/3">
                    <input
                        class="bg-slate-800 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-400 leading-tight focus:outline-none focus:bg-slate-900 focus:border-purple-500"
                        id="inline-full-name" type="text">
                </div>
            </div>
            <div class="md:flex md:items-center mb-6">
                <div class="md:w-1/3">
                    <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-username">
                        Email
                    </label>
                </div>
                <div class="md:w-2/3">
                    <input
                        class="bg-slate-800 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-400 leading-tight focus:outline-none focus:bg-slate-900 focus:border-purple-500"
                        id="inline-username" type="email">
                </div>
            </div>
            <div class="flex items-center md:flex md:items-center mb-6">

                <button class="" type="submit">
                    Sign Up
                </button>


            </div>
        </form>
    </div>
</template> -->

<template>
    <!-- THIS TEMPLATE WAS GENERATED BY COPILOT -->
    <!-- a horizontally and vertically aligned form -->
    <div class="container mx-auto flex items-center justify-center h-screen">
        <form class="w-full max-w-xs">
            <h1 class="cybershadow font-mono text-xs mb-2 text-green-700 font-bold drop-shadow-md shadow-blue-600/50">
                <pre>
                <code>
  _________.__                 ____ ___         
 /   _____/|__| ____   ____   |    |   \______  
 \_____  \ |  |/ ___\ /    \  |    |   /\____ \ 
 /        \|  / /_/  >   |  \ |    |  / |  |_> >
/_______  /|__\___  /|___|  / |______/  |   __/ 
        \/   /_____/      \/            |__|  
                </code>
                </pre>
            </h1>

            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-400 text-xs font-bold mb-2"
                        for="grid-first-name">
                        First Name
                    </label>
                    <input
                        class="appearance-none block w-full bg-slate-800 text-gray-400 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-slate-900"
                        id="grid-first-name" type="text" placeholder="Jane">
                </div>
                <div class="w-full md:w-1/2 px-3">
                    <label class="block uppercase tracking-wide text-gray-400 text-xs font-bold mb-2"
                        for="grid-last-name">
                        Last Name
                    </label>
                    <input
                        class="appearance-none block w-full bg-slate-800 text-gray-400 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-slate-900 focus:border-gray-500"
                        id="grid-last-name" type="text" placeholder="Doe">
                </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full px-3">
                    <label class="block uppercase tracking-wide text-gray-400 text-xs font-bold mb-2" for="grid-email">
                        Email
                    </label>
                    <input
                        class="appearance-none block w-full bg-slate-800 text-gray-400 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-slate-900 focus:border-gray-500"
                        id="grid-email" type="email" placeholder="Jane.Doe@pm.me">
                    <p class="text-gray-600 text-xs italic">We'll reach out soon!</p>
                </div>
            </div>
            <!-- <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full px-3">
                    <label class="block uppercase tracking-wide text-gray-400 text-xs font-bold mb-2"
                        for="grid-password">
                        Password
                    </label>
                    <input
                        class="appearance-none block w-full bg-slate-800 text-gray-400 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-slate-900 focus:border-gray-500"
                        id="grid-password" type="password" placeholder="******************">
                    <p class="text-gray-600 text-xs italic">Make it as long and as crazy as you'd like</p>
                </div>
            </div> -->
        </form>
    </div>
</template>